### PR TITLE
Bump runtime to 22.08

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by zorgiepoo** [comment]
Seems like I'm having trouble testing the 22.08 runtime:

```
msp@ubuntu:~/Desktop/Sky-Checkers/linux$ flatpak-builder --gpg-sign=$GPGKEY --repo=sc-repo --force-clean flatpak-build net.zgcoder.skycheckers.json
error: org.freedesktop.Platform/x86_64/22.08 not installed
Failed to init: Unable to find runtime org.freedesktop.Platform version 22.08
```

Tried to run some arbitrary commands to install 22.08 but probably didn't find the correct ones:

```
msp@ubuntu:~$ flatpak list
Name     Application ID        Version    Branch      Origin       Installation
Hello    org.flatpak.Hello                master      hello-origin user
Freedes… …freedesktop.Platform 19.08.15   19.08       flathub      system
Freedes… …freedesktop.Platform 21.08.18   21.08       flathub      system
default  …orm.GL.Debug.default            22.08       flathub      system
default  …orm.GL.Debug.default            22.08-extra flathub      system
default  ….Platform.GL.default            19.08       flathub      system
Mesa     ….Platform.GL.default 21.3.9     21.08       flathub      system
Mesa     ….Platform.GL.default 23.1.1     22.08       flathub      system
Mesa (E… ….Platform.GL.default 23.1.1     22.08-extra flathub      system
openh264 …op.Platform.openh264 2.1.0      2.0         flathub      system
openh264 …op.Platform.openh264 2.1.0      2.2.0       flathub      system
Freedes… org.freedesktop.Sdk   21.08.18   21.08       flathub      system
Freedes… org.freedesktop.Sdk   22.08.12.1 22.08       flathub      system
Yaru Gt… …g.gtk.Gtk3theme.Yaru            3.22        flathub      system
```

**Comment by bbhtt** [comment]
Yea, you need to install it before the build: `flatpak install org.freedesktop.Platform//22.08`

You can also try the test build below

bot, build

**Comment by bbhtt** [comment]
Hi @zorgiepoo any update here?

**Comment by zorgiepoo** [comment]
Sorry for the delay. My VM hasn't been touched in a while and I have to tinker with a bunch of flatpak commands I wrote in some notepad.. the commands I found using gpg have been problematic for me. I think the test build here may have expired, or I can't install it.

Anyway, I think I found a set of working commands for testing this:
```
# Alternatively to test:
flatpak remove --user -y net.zgcoder.skycheckers
flatpak-builder --repo=sc-repo --force-clean flatpak-build net.zgcoder.skycheckers.json
flatpak-builder --user --install --force-clean build-dir net.zgcoder.skycheckers.json
flatpak run net.zgcoder.skycheckers
```

A problem I think I am seeing is after updating the runtime version, the font rendering in my game is all corrupted and is no longer working.. If I revert changing the runtime version and repeat these steps then it works fine though.

Is SDL_ttf included in the freedesktop runtime? I can't find me specifying it anywhere. (if so, what versions of SDL and SDL_ttf does it include? I know I am presently building my own version of SDL, I may need to update that too..)


[edit]: This is a "bug" in my program I have to fix/investigate before updating runtime version.

**Comment by zorgiepoo** [comment]
Done in #3

**Comment by zorgiepoo** [comment]
I hope the new version gets automatically published to FlatHub. I tried logging in there and it required/wanted me to set up a .well-known directory on my nginx server which turned out to be a lot more complicated than I imagined so I gave up on that front.

**Comment by bbhtt** [comment]
That's for the verified checkmark, it'll be published ~4 hours from now. You can check with

```
flatpak remote-info flathub net.zgcoder.skycheckers

        ID: net.zgcoder.skycheckers
       Ref: app/net.zgcoder.skycheckers/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 1.6 MB
 Installed: 3.6 MB
   Runtime: org.freedesktop.Platform/x86_64/21.08
       Sdk: org.freedesktop.Sdk/x86_64/21.08

    Commit: 10e24b9fd5a348bd38a4399faa7b40d466292ae3cbd743de56a909f10d2aab4d
    Parent: a8b1d80aefc920f1291dc714b795450ad931708451e288e7b7c74e17a6a09136
   Subject: Bump runtime to 21.08 and update Sky Checkers to 1.3 (7504049b)
      Date: 2022-07-16 04:26:53 +0000
```

**Pull request closed without merging**
